version: '3.8'

services:
  db:
    image: postgres:11.0-alpine
    container_name: database
    environment:
      - POSTGRES_USER=$DB_USER
    restart: always
    ports:
      - "5432:5432"
    networks:
      - tg_bot
    volumes:
      - ./postgres:/var/lib/postgresql

  redis_cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --port $REDIS_PORT --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    env_file:
      - ".env"
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data
    networks:
      - tg_bot

  bot:
    image: krivse/imperial_bot:v1.31.8.23
#    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
#    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
#    build:
#      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: bash -c "alembic revision --autogenerate && alembic upgrade head && python3 -m bot"
    restart: always
    env_file:
      - .env
    networks:
    - tg_bot
    depends_on:
      - db
      - redis_cache

networks:
  tg_bot:
    driver: bridge

