version: '3.3'

services:
  db:
    image: postgres:11.0-alpine
    container_name: database
    environment:
      - POSTGRES_USER=$DB_USER
    restart: always
    ports:
      - "5432:5432"
    networks:
      - tg_bot
    volumes:
      - ./postgres:/var/lib/postgresql

  redis_cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --port $REDIS_PORT --save 20 1 --loglevel warning --r>
    env_file:
      - ".env"
    volumes:
      - ./cache:/data
    networks:
      - tg_bot

  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: bash -c "alembic upgrade head && python3 -m bot"
    restart: always
    env_file:
      - .env
    networks:
    - tg_bot
    depends_on:
      - db
      - redis_cache

networks:
  tg_bot:
    driver: bridge

