"""initial migration

Revision ID: 1c5a5f28149b
Revises: 277fed7e049d
Create Date: 2023-02-24 03:19:25.438466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5a5f28149b'
down_revision = '277fed7e049d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('player', sa.String(), nullable=True))
    op.drop_column('team', 'gamer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('gamer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('team', 'player')
    # ### end Alembic commands ###
