"""initial migration

Revision ID: 1fdc0ab698d1
Revises: 962ccb367aec
Create Date: 2023-02-24 02:54:11.958102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdc0ab698d1'
down_revision = '962ccb367aec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('avatar', sa.String(), nullable=True))
    op.drop_column('team', 'url_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('url_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('team', 'avatar')
    op.drop_column('team', 'age')
    # ### end Alembic commands ###
