"""initial migration

Revision ID: 277fed7e049d
Revises: 1fdc0ab698d1
Create Date: 2023-02-24 02:55:12.649749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277fed7e049d'
down_revision = '1fdc0ab698d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('current_club', sa.String(), nullable=True))
    op.add_column('team', sa.Column('previous_clubs', sa.String(), nullable=True))
    op.add_column('team', sa.Column('birthday', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'birthday')
    op.drop_column('team', 'previous_clubs')
    op.drop_column('team', 'current_club')
    # ### end Alembic commands ###
