"""initial migration

Revision ID: 962ccb367aec
Revises: 
Create Date: 2023-02-16 06:35:04.457923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962ccb367aec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('victory', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.Column('defeat', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('missed', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('up_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamer', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('penalty', sa.Integer(), nullable=True),
    sa.Column('assist', sa.Integer(), nullable=True),
    sa.Column('goalpen', sa.Integer(), nullable=True),
    sa.Column('autogoals', sa.Integer(), nullable=True),
    sa.Column('yellowcards', sa.Integer(), nullable=True),
    sa.Column('redcards', sa.Integer(), nullable=True),
    sa.Column('vrt', sa.Integer(), nullable=True),
    sa.Column('prg', sa.Integer(), nullable=True),
    sa.Column('url_photo', sa.String(), nullable=True),
    sa.Column('up_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('table_tournament')
    # ### end Alembic commands ###
